# Generated by Django 5.0 on 2024-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fullname')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram_id')),
                ('balance', models.BigIntegerField(default=0, null=True, verbose_name='Balance')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Telefon raqami')),
                ('ref_father', models.BigIntegerField(blank=True, null=True, verbose_name='ref_father')),
                ('register', models.BooleanField(default=False)),
            ],
        ),
    ]
