# Generated by Django 5.0 on 2024-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefon raqami'),
        ),
    ]
