# Generated by Django 5.0 on 2024-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_balance_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
