# Generated by Django 5.0 on 2024-11-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium',
        ),
    ]
