# Generated by Django 5.0 on 2024-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi va vaqti'),
        ),
    ]
