# Generated by Django 5.0 on 2024-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_promocode_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='activate', max_length=10),
        ),
    ]
