# Generated by Django 5.0 on 2024-11-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_promocode_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='user',
        ),
        migrations.AddField(
            model_name='promocode',
            name='user_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram_id'),
        ),
    ]
