# Generated by Django 5.0 on 2024-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_promocode_user_promocode_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Telegram_id'),
        ),
    ]
